FROM ruby:3.3.6-alpine

RUN apk update && apk add nodejs npm git build-base libpq-dev gcompat bash openssl-dev
WORKDIR /app

COPY web .

RUN bundle install

COPY entrypoints/worker.sh /usr/bin/
RUN chmod +x /usr/bin/worker.sh

ENTRYPOINT ["worker.sh"]
